# Generated by Django 3.2.9 on 2021-12-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_post_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
